// @flow

export const REGISTRATION_REQUESTED = "REGISTRATION_REQUESTED";
export const REGISTRATION_SUCCEEDED = "REGISTRATION_SUCCEEDED";
export const REGISTRATION_FAILED = "REGISTRATION_FAILED";

export const SIGN_IN_REQUESTED = "SIGN_IN_REQUESTED";
export const SIGN_IN_SUCCEEDED = "SIGN_IN_SUCCEEDED";
export const SIGN_IN_FAILED = "SIGN_IN_FAILED";
